# Generated by Django 5.1.3 on 2025-01-04 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduationproject',
            name='doctor',
            field=models.ForeignKey(limit_choices_to=models.Q(('profile__is_doctor', True)), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='graduationproject',
            name='students',
            field=models.ManyToManyField(limit_choices_to=models.Q(('profile__is_doctor', False), ('profile__is_teaching_assistant', False)), related_name='student_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='graduationproject',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='supervisor_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GraduationProjectReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='graduation_project.graduationproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'project')},
            },
        ),
    ]
