# Generated by Django 5.1.3 on 2025-01-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_project', '0003_graduationprojectreaction_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraduationProjectReaction',
        ),
    ]
