# Generated by Django 5.1.3 on 2025-01-04 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_project', '0004_delete_graduationprojectreaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationproject',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_project', to=settings.AUTH_USER_MODEL),
        ),
    ]
