# Generated by Django 4.2.18 on 2025-01-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_project', '0005_graduationproject_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationproject',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
