# Generated by Django 4.2.18 on 2025-01-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_project', '0006_graduationproject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationproject',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
