# Generated by Django 4.2.18 on 2025-01-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_project', '0007_graduationproject_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationproject',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
