# Generated by Django 4.2.18 on 2025-02-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_project', '0009_alter_graduationproject_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduationproject',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
    ]
