# Generated by Django 4.2.18 on 2025-02-11 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graduation_project', '0016_remove_graduationproject_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationproject',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_project', to=settings.AUTH_USER_MODEL),
        ),
    ]
