# Generated by Django 4.2.18 on 2025-02-11 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_project', '0022_alter_graduationproject_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
