# Generated by Django 4.2.18 on 2025-03-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_project', '0025_alter_graduationproject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationproject',
            name='title_ar',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
