# Generated by Django 4.2.18 on 2025-03-13 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_project', '0029_rename_images_graduationproject_main_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduationproject',
            old_name='main_image',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='graduationproject',
            name='pages_image',
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_image', to='graduation_project.graduationproject')),
            ],
        ),
    ]
