# Generated by Django 4.2.18 on 2025-03-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_project', '0030_rename_main_image_graduationproject_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduationproject',
            name='images',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط الصورة'),
        ),
    ]
