# Generated by Django 4.2.18 on 2025-05-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_project', '0032_alter_graduationproject_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationproject',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='projects/audio/'),
        ),
    ]
