# Generated by Django 5.1.3 on 2024-12-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='national_id',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
