# Generated by Django 5.1.3 on 2025-01-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='national_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
