# Generated by Django 4.2.18 on 2025-02-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn Link'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='porfolio_link',
            field=models.URLField(blank=True, null=True, verbose_name='Porfolio Link'),
        ),
    ]
