# Generated by Django 4.2.18 on 2025-02-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_linkedin_link_userprofile_porfolio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='instgram_link',
            field=models.URLField(blank=True, null=True, verbose_name='instagram Link'),
        ),
    ]
