# Generated by Django 4.2.18 on 2025-06-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activate', '0003_remove_activatelog_city_remove_activatelog_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activatelog',
            name='user_agent',
            field=models.CharField(max_length=500),
        ),
    ]
