# Generated by Django 4.2.18 on 2025-06-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activate', '0004_alter_activatelog_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='activatelog',
            name='browser_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activatelog',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activatelog',
            name='ip_address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activatelog',
            name='method',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='activatelog',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
